version: "3.7"

x-service-volumes: &service-volumes
  - ./:/app/:rw,cached

volumes:
  db-data: {}

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: website
    volumes: *service-volumes
    env_file:
      - .env/.django
      - .env/.postgres
    depends_on:
      - postgres
    ports:
    - "8000:8000"

  postgres:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    env_file:
      - .env/.django
    volumes:
    - db-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env/.django
    container_name: celery
    depends_on:
      - rabbitmq
      - postgres
    command: celery -A website worker -l INFO