# Generated by Django 3.1.7 on 2021-02-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название хобби')),
                ('normalized_name', models.CharField(max_length=64, unique=True, verbose_name='Нормализованное название хобби')),
            ],
            options={
                'verbose_name': 'Хобби',
                'verbose_name_plural': 'Хобби',
            },
        ),
        migrations.AlterModelOptions(
            name='userpersona',
            options={'verbose_name': 'Роль', 'verbose_name_plural': 'Роли'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='userpersona',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='userpersona',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Название роли'),
        ),
        migrations.AlterField(
            model_name='userpersona',
            name='normalized_name',
            field=models.CharField(max_length=64, unique=True, verbose_name='Нормализованное название роли'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_full_name_displayed',
            field=models.BooleanField(default=True, verbose_name='Отображать ли полное имя пользователя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Вебсайт пользователя'),
        ),
        migrations.AddIndex(
            model_name='userpersona',
            index=models.Index(fields=['name'], name='accounts_us_name_7c40b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='accounts_us_user_id_806298_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterest',
            index=models.Index(fields=['name'], name='accounts_us_name_7a20a8_idx'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='accounts.UserInterest'),
        ),
    ]
