# Generated by Django 3.1.7 on 2021-03-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210224_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на LinkedIn'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на Twitter'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на YouTube'),
        ),
    ]
